// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebPageStat.proto

package com.amit.webster.api;

public final class WebPageStat {
  private WebPageStat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebPageStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amit.webster.api.WebPageStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string completeUrl = 1;</code>
     */
    boolean hasCompleteUrl();
    /**
     * <code>required string completeUrl = 1;</code>
     */
    java.lang.String getCompleteUrl();
    /**
     * <code>required string completeUrl = 1;</code>
     */
    com.google.protobuf.ByteString
        getCompleteUrlBytes();

    /**
     * <code>required string baseUrl = 2;</code>
     */
    boolean hasBaseUrl();
    /**
     * <code>required string baseUrl = 2;</code>
     */
    java.lang.String getBaseUrl();
    /**
     * <code>required string baseUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getBaseUrlBytes();

    /**
     * <code>required string header = 3;</code>
     */
    boolean hasHeader();
    /**
     * <code>required string header = 3;</code>
     */
    java.lang.String getHeader();
    /**
     * <code>required string header = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeaderBytes();

    /**
     * <code>required int32 likes = 4;</code>
     */
    boolean hasLikes();
    /**
     * <code>required int32 likes = 4;</code>
     */
    int getLikes();

    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData> 
        getMetadataList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    com.amit.webster.api.WebPageStat.WebPageStats.MetaData getMetadata(int index);
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    int getMetadataCount();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder> 
        getMetadataOrBuilderList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder getMetadataOrBuilder(
        int index);

    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags> 
        getTagList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    com.amit.webster.api.WebPageStat.WebPageStats.Tags getTag(int index);
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    int getTagCount();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder> 
        getTagOrBuilderList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder getTagOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.amit.webster.api.WebPageStats}
   */
  public static final class WebPageStats extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.amit.webster.api.WebPageStats)
      WebPageStatsOrBuilder {
    // Use WebPageStats.newBuilder() to construct.
    private WebPageStats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebPageStats(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebPageStats defaultInstance;
    public static WebPageStats getDefaultInstance() {
      return defaultInstance;
    }

    public WebPageStats getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebPageStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              completeUrl_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              baseUrl_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              header_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              likes_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                tag_ = new java.util.ArrayList<com.amit.webster.api.WebPageStat.WebPageStats.Tags>();
                mutable_bitField0_ |= 0x00000020;
              }
              tag_.add(input.readMessage(com.amit.webster.api.WebPageStat.WebPageStats.Tags.PARSER, extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                metadata_ = new java.util.ArrayList<com.amit.webster.api.WebPageStat.WebPageStats.MetaData>();
                mutable_bitField0_ |= 0x00000010;
              }
              metadata_.add(input.readMessage(com.amit.webster.api.WebPageStat.WebPageStats.MetaData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          metadata_ = java.util.Collections.unmodifiableList(metadata_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amit.webster.api.WebPageStat.WebPageStats.class, com.amit.webster.api.WebPageStat.WebPageStats.Builder.class);
    }

    public static com.google.protobuf.Parser<WebPageStats> PARSER =
        new com.google.protobuf.AbstractParser<WebPageStats>() {
      public WebPageStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebPageStats(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebPageStats> getParserForType() {
      return PARSER;
    }

    public interface MetaDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.amit.webster.api.WebPageStats.MetaData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string metaData = 1;</code>
       */
      boolean hasMetaData();
      /**
       * <code>optional string metaData = 1;</code>
       */
      java.lang.String getMetaData();
      /**
       * <code>optional string metaData = 1;</code>
       */
      com.google.protobuf.ByteString
          getMetaDataBytes();
    }
    /**
     * Protobuf type {@code com.amit.webster.api.WebPageStats.MetaData}
     */
    public static final class MetaData extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.amit.webster.api.WebPageStats.MetaData)
        MetaDataOrBuilder {
      // Use MetaData.newBuilder() to construct.
      private MetaData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MetaData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MetaData defaultInstance;
      public static MetaData getDefaultInstance() {
        return defaultInstance;
      }

      public MetaData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MetaData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                metaData_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_MetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amit.webster.api.WebPageStat.WebPageStats.MetaData.class, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder.class);
      }

      public static com.google.protobuf.Parser<MetaData> PARSER =
          new com.google.protobuf.AbstractParser<MetaData>() {
        public MetaData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetaData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MetaData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int METADATA_FIELD_NUMBER = 1;
      private java.lang.Object metaData_;
      /**
       * <code>optional string metaData = 1;</code>
       */
      public boolean hasMetaData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string metaData = 1;</code>
       */
      public java.lang.String getMetaData() {
        java.lang.Object ref = metaData_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            metaData_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string metaData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMetaDataBytes() {
        java.lang.Object ref = metaData_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metaData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        metaData_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMetaDataBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMetaDataBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.MetaData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.amit.webster.api.WebPageStat.WebPageStats.MetaData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.amit.webster.api.WebPageStats.MetaData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.amit.webster.api.WebPageStats.MetaData)
          com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_MetaData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.amit.webster.api.WebPageStat.WebPageStats.MetaData.class, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder.class);
        }

        // Construct using com.amit.webster.api.WebPageStat.WebPageStats.MetaData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          metaData_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor;
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.MetaData getDefaultInstanceForType() {
          return com.amit.webster.api.WebPageStat.WebPageStats.MetaData.getDefaultInstance();
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.MetaData build() {
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.MetaData buildPartial() {
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData result = new com.amit.webster.api.WebPageStat.WebPageStats.MetaData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.metaData_ = metaData_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.amit.webster.api.WebPageStat.WebPageStats.MetaData) {
            return mergeFrom((com.amit.webster.api.WebPageStat.WebPageStats.MetaData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.amit.webster.api.WebPageStat.WebPageStats.MetaData other) {
          if (other == com.amit.webster.api.WebPageStat.WebPageStats.MetaData.getDefaultInstance()) return this;
          if (other.hasMetaData()) {
            bitField0_ |= 0x00000001;
            metaData_ = other.metaData_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.amit.webster.api.WebPageStat.WebPageStats.MetaData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object metaData_ = "";
        /**
         * <code>optional string metaData = 1;</code>
         */
        public boolean hasMetaData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string metaData = 1;</code>
         */
        public java.lang.String getMetaData() {
          java.lang.Object ref = metaData_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              metaData_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string metaData = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMetaDataBytes() {
          java.lang.Object ref = metaData_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            metaData_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string metaData = 1;</code>
         */
        public Builder setMetaData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          metaData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string metaData = 1;</code>
         */
        public Builder clearMetaData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          metaData_ = getDefaultInstance().getMetaData();
          onChanged();
          return this;
        }
        /**
         * <code>optional string metaData = 1;</code>
         */
        public Builder setMetaDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          metaData_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.amit.webster.api.WebPageStats.MetaData)
      }

      static {
        defaultInstance = new MetaData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.amit.webster.api.WebPageStats.MetaData)
    }

    public interface TagsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.amit.webster.api.WebPageStats.Tags)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string tag = 1;</code>
       */
      boolean hasTag();
      /**
       * <code>optional string tag = 1;</code>
       */
      java.lang.String getTag();
      /**
       * <code>optional string tag = 1;</code>
       */
      com.google.protobuf.ByteString
          getTagBytes();
    }
    /**
     * Protobuf type {@code com.amit.webster.api.WebPageStats.Tags}
     */
    public static final class Tags extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.amit.webster.api.WebPageStats.Tags)
        TagsOrBuilder {
      // Use Tags.newBuilder() to construct.
      private Tags(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Tags(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Tags defaultInstance;
      public static Tags getDefaultInstance() {
        return defaultInstance;
      }

      public Tags getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Tags(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                tag_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_Tags_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amit.webster.api.WebPageStat.WebPageStats.Tags.class, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder.class);
      }

      public static com.google.protobuf.Parser<Tags> PARSER =
          new com.google.protobuf.AbstractParser<Tags>() {
        public Tags parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tags(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Tags> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TAG_FIELD_NUMBER = 1;
      private java.lang.Object tag_;
      /**
       * <code>optional string tag = 1;</code>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string tag = 1;</code>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tag_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string tag = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        tag_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTagBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTagBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageStat.WebPageStats.Tags parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.amit.webster.api.WebPageStat.WebPageStats.Tags prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.amit.webster.api.WebPageStats.Tags}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.amit.webster.api.WebPageStats.Tags)
          com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_Tags_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.amit.webster.api.WebPageStat.WebPageStats.Tags.class, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder.class);
        }

        // Construct using com.amit.webster.api.WebPageStat.WebPageStats.Tags.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          tag_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor;
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.Tags getDefaultInstanceForType() {
          return com.amit.webster.api.WebPageStat.WebPageStats.Tags.getDefaultInstance();
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.Tags build() {
          com.amit.webster.api.WebPageStat.WebPageStats.Tags result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.amit.webster.api.WebPageStat.WebPageStats.Tags buildPartial() {
          com.amit.webster.api.WebPageStat.WebPageStats.Tags result = new com.amit.webster.api.WebPageStat.WebPageStats.Tags(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.tag_ = tag_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.amit.webster.api.WebPageStat.WebPageStats.Tags) {
            return mergeFrom((com.amit.webster.api.WebPageStat.WebPageStats.Tags)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.amit.webster.api.WebPageStat.WebPageStats.Tags other) {
          if (other == com.amit.webster.api.WebPageStat.WebPageStats.Tags.getDefaultInstance()) return this;
          if (other.hasTag()) {
            bitField0_ |= 0x00000001;
            tag_ = other.tag_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.amit.webster.api.WebPageStat.WebPageStats.Tags parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.amit.webster.api.WebPageStat.WebPageStats.Tags) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object tag_ = "";
        /**
         * <code>optional string tag = 1;</code>
         */
        public boolean hasTag() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public java.lang.String getTag() {
          java.lang.Object ref = tag_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              tag_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTagBytes() {
          java.lang.Object ref = tag_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            tag_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTag(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          tag_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder clearTag() {
          bitField0_ = (bitField0_ & ~0x00000001);
          tag_ = getDefaultInstance().getTag();
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTagBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          tag_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.amit.webster.api.WebPageStats.Tags)
      }

      static {
        defaultInstance = new Tags(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.amit.webster.api.WebPageStats.Tags)
    }

    private int bitField0_;
    public static final int COMPLETEURL_FIELD_NUMBER = 1;
    private java.lang.Object completeUrl_;
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public boolean hasCompleteUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public java.lang.String getCompleteUrl() {
      java.lang.Object ref = completeUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          completeUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompleteUrlBytes() {
      java.lang.Object ref = completeUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        completeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEURL_FIELD_NUMBER = 2;
    private java.lang.Object baseUrl_;
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public boolean hasBaseUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          baseUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADER_FIELD_NUMBER = 3;
    private java.lang.Object header_;
    /**
     * <code>required string header = 3;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string header = 3;</code>
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          header_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string header = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKES_FIELD_NUMBER = 4;
    private int likes_;
    /**
     * <code>required int32 likes = 4;</code>
     */
    public boolean hasLikes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 likes = 4;</code>
     */
    public int getLikes() {
      return likes_;
    }

    public static final int METADATA_FIELD_NUMBER = 7;
    private java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData> metadata_;
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData> getMetadataList() {
      return metadata_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    public java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder> 
        getMetadataOrBuilderList() {
      return metadata_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    public int getMetadataCount() {
      return metadata_.size();
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    public com.amit.webster.api.WebPageStat.WebPageStats.MetaData getMetadata(int index) {
      return metadata_.get(index);
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
     */
    public com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder getMetadataOrBuilder(
        int index) {
      return metadata_.get(index);
    }

    public static final int TAG_FIELD_NUMBER = 6;
    private java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags> tag_;
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags> getTagList() {
      return tag_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    public java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    public com.amit.webster.api.WebPageStat.WebPageStats.Tags getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
     */
    public com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }

    private void initFields() {
      completeUrl_ = "";
      baseUrl_ = "";
      header_ = "";
      likes_ = 0;
      metadata_ = java.util.Collections.emptyList();
      tag_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCompleteUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBaseUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLikes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCompleteUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBaseUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHeaderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, likes_);
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(6, tag_.get(i));
      }
      for (int i = 0; i < metadata_.size(); i++) {
        output.writeMessage(7, metadata_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCompleteUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBaseUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHeaderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, likes_);
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, tag_.get(i));
      }
      for (int i = 0; i < metadata_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, metadata_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amit.webster.api.WebPageStat.WebPageStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.amit.webster.api.WebPageStat.WebPageStats prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amit.webster.api.WebPageStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amit.webster.api.WebPageStats)
        com.amit.webster.api.WebPageStat.WebPageStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amit.webster.api.WebPageStat.WebPageStats.class, com.amit.webster.api.WebPageStat.WebPageStats.Builder.class);
      }

      // Construct using com.amit.webster.api.WebPageStat.WebPageStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetadataFieldBuilder();
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        completeUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        baseUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        header_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        likes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          metadataBuilder_.clear();
        }
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          tagBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amit.webster.api.WebPageStat.internal_static_com_amit_webster_api_WebPageStats_descriptor;
      }

      public com.amit.webster.api.WebPageStat.WebPageStats getDefaultInstanceForType() {
        return com.amit.webster.api.WebPageStat.WebPageStats.getDefaultInstance();
      }

      public com.amit.webster.api.WebPageStat.WebPageStats build() {
        com.amit.webster.api.WebPageStat.WebPageStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.amit.webster.api.WebPageStat.WebPageStats buildPartial() {
        com.amit.webster.api.WebPageStat.WebPageStats result = new com.amit.webster.api.WebPageStat.WebPageStats(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.completeUrl_ = completeUrl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.baseUrl_ = baseUrl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.header_ = header_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.likes_ = likes_;
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            metadata_ = java.util.Collections.unmodifiableList(metadata_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amit.webster.api.WebPageStat.WebPageStats) {
          return mergeFrom((com.amit.webster.api.WebPageStat.WebPageStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amit.webster.api.WebPageStat.WebPageStats other) {
        if (other == com.amit.webster.api.WebPageStat.WebPageStats.getDefaultInstance()) return this;
        if (other.hasCompleteUrl()) {
          bitField0_ |= 0x00000001;
          completeUrl_ = other.completeUrl_;
          onChanged();
        }
        if (other.hasBaseUrl()) {
          bitField0_ |= 0x00000002;
          baseUrl_ = other.baseUrl_;
          onChanged();
        }
        if (other.hasHeader()) {
          bitField0_ |= 0x00000004;
          header_ = other.header_;
          onChanged();
        }
        if (other.hasLikes()) {
          setLikes(other.getLikes());
        }
        if (metadataBuilder_ == null) {
          if (!other.metadata_.isEmpty()) {
            if (metadata_.isEmpty()) {
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMetadataIsMutable();
              metadata_.addAll(other.metadata_);
            }
            onChanged();
          }
        } else {
          if (!other.metadata_.isEmpty()) {
            if (metadataBuilder_.isEmpty()) {
              metadataBuilder_.dispose();
              metadataBuilder_ = null;
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000010);
              metadataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetadataFieldBuilder() : null;
            } else {
              metadataBuilder_.addAllMessages(other.metadata_);
            }
          }
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000020);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCompleteUrl()) {
          
          return false;
        }
        if (!hasBaseUrl()) {
          
          return false;
        }
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasLikes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amit.webster.api.WebPageStat.WebPageStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amit.webster.api.WebPageStat.WebPageStats) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object completeUrl_ = "";
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public boolean hasCompleteUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public java.lang.String getCompleteUrl() {
        java.lang.Object ref = completeUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            completeUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCompleteUrlBytes() {
        java.lang.Object ref = completeUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          completeUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder setCompleteUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        completeUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder clearCompleteUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        completeUrl_ = getDefaultInstance().getCompleteUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder setCompleteUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        completeUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object baseUrl_ = "";
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public boolean hasBaseUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public java.lang.String getBaseUrl() {
        java.lang.Object ref = baseUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            baseUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBaseUrlBytes() {
        java.lang.Object ref = baseUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder setBaseUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        baseUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder clearBaseUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        baseUrl_ = getDefaultInstance().getBaseUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder setBaseUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        baseUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object header_ = "";
      /**
       * <code>required string header = 3;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string header = 3;</code>
       */
      public java.lang.String getHeader() {
        java.lang.Object ref = header_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            header_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string header = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeaderBytes() {
        java.lang.Object ref = header_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          header_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder setHeader(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        header_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000004);
        header_ = getDefaultInstance().getHeader();
        onChanged();
        return this;
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder setHeaderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        header_ = value;
        onChanged();
        return this;
      }

      private int likes_ ;
      /**
       * <code>required int32 likes = 4;</code>
       */
      public boolean hasLikes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 likes = 4;</code>
       */
      public int getLikes() {
        return likes_;
      }
      /**
       * <code>required int32 likes = 4;</code>
       */
      public Builder setLikes(int value) {
        bitField0_ |= 0x00000008;
        likes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 likes = 4;</code>
       */
      public Builder clearLikes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        likes_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData> metadata_ =
        java.util.Collections.emptyList();
      private void ensureMetadataIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          metadata_ = new java.util.ArrayList<com.amit.webster.api.WebPageStat.WebPageStats.MetaData>(metadata_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder, com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder> metadataBuilder_;

      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData> getMetadataList() {
        if (metadataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metadata_);
        } else {
          return metadataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public int getMetadataCount() {
        if (metadataBuilder_ == null) {
          return metadata_.size();
        } else {
          return metadataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.MetaData getMetadata(int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);
        } else {
          return metadataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder setMetadata(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.MetaData value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.set(index, value);
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder setMetadata(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.set(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder addMetadata(com.amit.webster.api.WebPageStat.WebPageStats.MetaData value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder addMetadata(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.MetaData value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(index, value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder addMetadata(
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder addMetadata(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder addAllMetadata(
          java.lang.Iterable<? extends com.amit.webster.api.WebPageStat.WebPageStats.MetaData> values) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metadata_);
          onChanged();
        } else {
          metadataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          metadataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public Builder removeMetadata(int index) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.remove(index);
          onChanged();
        } else {
          metadataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder getMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder getMetadataOrBuilder(
          int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);  } else {
          return metadataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder> 
           getMetadataOrBuilderList() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metadata_);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder addMetadataBuilder() {
        return getMetadataFieldBuilder().addBuilder(
            com.amit.webster.api.WebPageStat.WebPageStats.MetaData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder addMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().addBuilder(
            index, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.MetaData metadata = 7;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder> 
           getMetadataBuilderList() {
        return getMetadataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageStat.WebPageStats.MetaData, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder, com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.amit.webster.api.WebPageStat.WebPageStats.MetaData, com.amit.webster.api.WebPageStat.WebPageStats.MetaData.Builder, com.amit.webster.api.WebPageStat.WebPageStats.MetaDataOrBuilder>(
                  metadata_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }

      private java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          tag_ = new java.util.ArrayList<com.amit.webster.api.WebPageStat.WebPageStats.Tags>(tag_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageStat.WebPageStats.Tags, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder, com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder> tagBuilder_;

      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.Tags getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder setTag(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder setTag(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder addTag(com.amit.webster.api.WebPageStat.WebPageStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          int index, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<? extends com.amit.webster.api.WebPageStat.WebPageStats.Tags> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public java.util.List<? extends com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            com.amit.webster.api.WebPageStat.WebPageStats.Tags.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, com.amit.webster.api.WebPageStat.WebPageStats.Tags.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageStats.Tags tag = 6;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageStat.WebPageStats.Tags, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder, com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.amit.webster.api.WebPageStat.WebPageStats.Tags, com.amit.webster.api.WebPageStat.WebPageStats.Tags.Builder, com.amit.webster.api.WebPageStat.WebPageStats.TagsOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.amit.webster.api.WebPageStats)
    }

    static {
      defaultInstance = new WebPageStats(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.amit.webster.api.WebPageStats)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amit_webster_api_WebPageStats_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amit_webster_api_WebPageStats_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amit_webster_api_WebPageStats_MetaData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amit_webster_api_WebPageStats_Tags_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021WebPageStat.proto\022\024com.amit.webster.ap" +
      "i\"\373\001\n\014WebPageStats\022\023\n\013completeUrl\030\001 \002(\t\022" +
      "\017\n\007baseUrl\030\002 \002(\t\022\016\n\006header\030\003 \002(\t\022\r\n\005like" +
      "s\030\004 \002(\005\022=\n\010metadata\030\007 \003(\0132+.com.amit.web" +
      "ster.api.WebPageStats.MetaData\0224\n\003tag\030\006 " +
      "\003(\0132\'.com.amit.webster.api.WebPageStats." +
      "Tags\032\034\n\010MetaData\022\020\n\010metaData\030\001 \001(\t\032\023\n\004Ta" +
      "gs\022\013\n\003tag\030\001 \001(\tB#\n\024com.amit.webster.apiB" +
      "\013WebPageStat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_amit_webster_api_WebPageStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amit_webster_api_WebPageStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amit_webster_api_WebPageStats_descriptor,
        new java.lang.String[] { "CompleteUrl", "BaseUrl", "Header", "Likes", "Metadata", "Tag", });
    internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor =
      internal_static_com_amit_webster_api_WebPageStats_descriptor.getNestedTypes().get(0);
    internal_static_com_amit_webster_api_WebPageStats_MetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amit_webster_api_WebPageStats_MetaData_descriptor,
        new java.lang.String[] { "MetaData", });
    internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor =
      internal_static_com_amit_webster_api_WebPageStats_descriptor.getNestedTypes().get(1);
    internal_static_com_amit_webster_api_WebPageStats_Tags_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amit_webster_api_WebPageStats_Tags_descriptor,
        new java.lang.String[] { "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
