// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebPageUserStat.proto

package com.amit.webster.api;

public final class WebPageUserStat {
  private WebPageUserStat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebPageUserStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amit.webster.api.WebPageUserStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string userId = 7;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 7;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>required string completeUrl = 1;</code>
     */
    boolean hasCompleteUrl();
    /**
     * <code>required string completeUrl = 1;</code>
     */
    java.lang.String getCompleteUrl();
    /**
     * <code>required string completeUrl = 1;</code>
     */
    com.google.protobuf.ByteString
        getCompleteUrlBytes();

    /**
     * <code>required string baseUrl = 2;</code>
     */
    boolean hasBaseUrl();
    /**
     * <code>required string baseUrl = 2;</code>
     */
    java.lang.String getBaseUrl();
    /**
     * <code>required string baseUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getBaseUrlBytes();

    /**
     * <code>required string header = 3;</code>
     */
    boolean hasHeader();
    /**
     * <code>required string header = 3;</code>
     */
    java.lang.String getHeader();
    /**
     * <code>required string header = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeaderBytes();

    /**
     * <code>required bool like = 4;</code>
     */
    boolean hasLike();
    /**
     * <code>required bool like = 4;</code>
     */
    boolean getLike();

    /**
     * <code>optional string note = 5;</code>
     */
    boolean hasNote();
    /**
     * <code>optional string note = 5;</code>
     */
    java.lang.String getNote();
    /**
     * <code>optional string note = 5;</code>
     */
    com.google.protobuf.ByteString
        getNoteBytes();

    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> 
        getTagList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags getTag(int index);
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    int getTagCount();
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    java.util.List<? extends com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder> 
        getTagOrBuilderList();
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder getTagOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.amit.webster.api.WebPageUserStats}
   */
  public static final class WebPageUserStats extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.amit.webster.api.WebPageUserStats)
      WebPageUserStatsOrBuilder {
    // Use WebPageUserStats.newBuilder() to construct.
    private WebPageUserStats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebPageUserStats(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebPageUserStats defaultInstance;
    public static WebPageUserStats getDefaultInstance() {
      return defaultInstance;
    }

    public WebPageUserStats getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebPageUserStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              completeUrl_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              baseUrl_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              header_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000010;
              like_ = input.readBool();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              note_ = bs;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                tag_ = new java.util.ArrayList<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags>();
                mutable_bitField0_ |= 0x00000040;
              }
              tag_.add(input.readMessage(com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.PARSER, extensionRegistry));
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amit.webster.api.WebPageUserStat.WebPageUserStats.class, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Builder.class);
    }

    public static com.google.protobuf.Parser<WebPageUserStats> PARSER =
        new com.google.protobuf.AbstractParser<WebPageUserStats>() {
      public WebPageUserStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebPageUserStats(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebPageUserStats> getParserForType() {
      return PARSER;
    }

    public interface TagsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.amit.webster.api.WebPageUserStats.Tags)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string tag = 1;</code>
       */
      boolean hasTag();
      /**
       * <code>optional string tag = 1;</code>
       */
      java.lang.String getTag();
      /**
       * <code>optional string tag = 1;</code>
       */
      com.google.protobuf.ByteString
          getTagBytes();
    }
    /**
     * Protobuf type {@code com.amit.webster.api.WebPageUserStats.Tags}
     */
    public static final class Tags extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.amit.webster.api.WebPageUserStats.Tags)
        TagsOrBuilder {
      // Use Tags.newBuilder() to construct.
      private Tags(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Tags(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Tags defaultInstance;
      public static Tags getDefaultInstance() {
        return defaultInstance;
      }

      public Tags getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Tags(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                tag_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_Tags_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.class, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder.class);
      }

      public static com.google.protobuf.Parser<Tags> PARSER =
          new com.google.protobuf.AbstractParser<Tags>() {
        public Tags parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tags(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Tags> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TAG_FIELD_NUMBER = 1;
      private java.lang.Object tag_;
      /**
       * <code>optional string tag = 1;</code>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string tag = 1;</code>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tag_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string tag = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        tag_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTagBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTagBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.amit.webster.api.WebPageUserStats.Tags}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.amit.webster.api.WebPageUserStats.Tags)
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_Tags_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.class, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder.class);
        }

        // Construct using com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          tag_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor;
        }

        public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags getDefaultInstanceForType() {
          return com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.getDefaultInstance();
        }

        public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags build() {
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags buildPartial() {
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags result = new com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.tag_ = tag_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags) {
            return mergeFrom((com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags other) {
          if (other == com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.getDefaultInstance()) return this;
          if (other.hasTag()) {
            bitField0_ |= 0x00000001;
            tag_ = other.tag_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object tag_ = "";
        /**
         * <code>optional string tag = 1;</code>
         */
        public boolean hasTag() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public java.lang.String getTag() {
          java.lang.Object ref = tag_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              tag_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTagBytes() {
          java.lang.Object ref = tag_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            tag_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTag(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          tag_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder clearTag() {
          bitField0_ = (bitField0_ & ~0x00000001);
          tag_ = getDefaultInstance().getTag();
          onChanged();
          return this;
        }
        /**
         * <code>optional string tag = 1;</code>
         */
        public Builder setTagBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          tag_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.amit.webster.api.WebPageUserStats.Tags)
      }

      static {
        defaultInstance = new Tags(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.amit.webster.api.WebPageUserStats.Tags)
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 7;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 7;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 7;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPLETEURL_FIELD_NUMBER = 1;
    private java.lang.Object completeUrl_;
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public boolean hasCompleteUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public java.lang.String getCompleteUrl() {
      java.lang.Object ref = completeUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          completeUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string completeUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompleteUrlBytes() {
      java.lang.Object ref = completeUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        completeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEURL_FIELD_NUMBER = 2;
    private java.lang.Object baseUrl_;
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public boolean hasBaseUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          baseUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string baseUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADER_FIELD_NUMBER = 3;
    private java.lang.Object header_;
    /**
     * <code>required string header = 3;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string header = 3;</code>
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          header_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string header = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKE_FIELD_NUMBER = 4;
    private boolean like_;
    /**
     * <code>required bool like = 4;</code>
     */
    public boolean hasLike() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool like = 4;</code>
     */
    public boolean getLike() {
      return like_;
    }

    public static final int NOTE_FIELD_NUMBER = 5;
    private java.lang.Object note_;
    /**
     * <code>optional string note = 5;</code>
     */
    public boolean hasNote() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string note = 5;</code>
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          note_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string note = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_FIELD_NUMBER = 6;
    private java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> tag_;
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    public java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> getTagList() {
      return tag_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    public java.util.List<? extends com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
     */
    public com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }

    private void initFields() {
      userId_ = "";
      completeUrl_ = "";
      baseUrl_ = "";
      header_ = "";
      like_ = false;
      note_ = "";
      tag_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompleteUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBaseUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLike()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(1, getCompleteUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(2, getBaseUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(3, getHeaderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(4, like_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(5, getNoteBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(6, tag_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(7, getUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCompleteUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBaseUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHeaderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, like_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNoteBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, tag_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amit.webster.api.WebPageUserStat.WebPageUserStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.amit.webster.api.WebPageUserStat.WebPageUserStats prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amit.webster.api.WebPageUserStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amit.webster.api.WebPageUserStats)
        com.amit.webster.api.WebPageUserStat.WebPageUserStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amit.webster.api.WebPageUserStat.WebPageUserStats.class, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Builder.class);
      }

      // Construct using com.amit.webster.api.WebPageUserStat.WebPageUserStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        completeUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        baseUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        header_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        like_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        note_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          tagBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amit.webster.api.WebPageUserStat.internal_static_com_amit_webster_api_WebPageUserStats_descriptor;
      }

      public com.amit.webster.api.WebPageUserStat.WebPageUserStats getDefaultInstanceForType() {
        return com.amit.webster.api.WebPageUserStat.WebPageUserStats.getDefaultInstance();
      }

      public com.amit.webster.api.WebPageUserStat.WebPageUserStats build() {
        com.amit.webster.api.WebPageUserStat.WebPageUserStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.amit.webster.api.WebPageUserStat.WebPageUserStats buildPartial() {
        com.amit.webster.api.WebPageUserStat.WebPageUserStats result = new com.amit.webster.api.WebPageUserStat.WebPageUserStats(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.completeUrl_ = completeUrl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.baseUrl_ = baseUrl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.header_ = header_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.like_ = like_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.note_ = note_;
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amit.webster.api.WebPageUserStat.WebPageUserStats) {
          return mergeFrom((com.amit.webster.api.WebPageUserStat.WebPageUserStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amit.webster.api.WebPageUserStat.WebPageUserStats other) {
        if (other == com.amit.webster.api.WebPageUserStat.WebPageUserStats.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasCompleteUrl()) {
          bitField0_ |= 0x00000002;
          completeUrl_ = other.completeUrl_;
          onChanged();
        }
        if (other.hasBaseUrl()) {
          bitField0_ |= 0x00000004;
          baseUrl_ = other.baseUrl_;
          onChanged();
        }
        if (other.hasHeader()) {
          bitField0_ |= 0x00000008;
          header_ = other.header_;
          onChanged();
        }
        if (other.hasLike()) {
          setLike(other.getLike());
        }
        if (other.hasNote()) {
          bitField0_ |= 0x00000020;
          note_ = other.note_;
          onChanged();
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000040);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasCompleteUrl()) {
          
          return false;
        }
        if (!hasBaseUrl()) {
          
          return false;
        }
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasLike()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amit.webster.api.WebPageUserStat.WebPageUserStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amit.webster.api.WebPageUserStat.WebPageUserStats) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 7;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userId = 7;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 7;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 7;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 7;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object completeUrl_ = "";
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public boolean hasCompleteUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public java.lang.String getCompleteUrl() {
        java.lang.Object ref = completeUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            completeUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCompleteUrlBytes() {
        java.lang.Object ref = completeUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          completeUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder setCompleteUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        completeUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder clearCompleteUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        completeUrl_ = getDefaultInstance().getCompleteUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string completeUrl = 1;</code>
       */
      public Builder setCompleteUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        completeUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object baseUrl_ = "";
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public boolean hasBaseUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public java.lang.String getBaseUrl() {
        java.lang.Object ref = baseUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            baseUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBaseUrlBytes() {
        java.lang.Object ref = baseUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder setBaseUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        baseUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder clearBaseUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        baseUrl_ = getDefaultInstance().getBaseUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string baseUrl = 2;</code>
       */
      public Builder setBaseUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        baseUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object header_ = "";
      /**
       * <code>required string header = 3;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string header = 3;</code>
       */
      public java.lang.String getHeader() {
        java.lang.Object ref = header_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            header_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string header = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeaderBytes() {
        java.lang.Object ref = header_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          header_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder setHeader(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        header_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000008);
        header_ = getDefaultInstance().getHeader();
        onChanged();
        return this;
      }
      /**
       * <code>required string header = 3;</code>
       */
      public Builder setHeaderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        header_ = value;
        onChanged();
        return this;
      }

      private boolean like_ ;
      /**
       * <code>required bool like = 4;</code>
       */
      public boolean hasLike() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool like = 4;</code>
       */
      public boolean getLike() {
        return like_;
      }
      /**
       * <code>required bool like = 4;</code>
       */
      public Builder setLike(boolean value) {
        bitField0_ |= 0x00000010;
        like_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool like = 4;</code>
       */
      public Builder clearLike() {
        bitField0_ = (bitField0_ & ~0x00000010);
        like_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object note_ = "";
      /**
       * <code>optional string note = 5;</code>
       */
      public boolean hasNote() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string note = 5;</code>
       */
      public java.lang.String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            note_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string note = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNoteBytes() {
        java.lang.Object ref = note_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          note_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string note = 5;</code>
       */
      public Builder setNote(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        note_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string note = 5;</code>
       */
      public Builder clearNote() {
        bitField0_ = (bitField0_ & ~0x00000020);
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      /**
       * <code>optional string note = 5;</code>
       */
      public Builder setNoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        note_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          tag_ = new java.util.ArrayList<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags>(tag_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder, com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder> tagBuilder_;

      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder setTag(
          int index, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder setTag(
          int index, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder addTag(com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          int index, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder addTag(
          int index, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<? extends com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public java.util.List<? extends com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amit.webster.api.WebPageUserStats.Tags tag = 6;</code>
       */
      public java.util.List<com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder, com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags, com.amit.webster.api.WebPageUserStat.WebPageUserStats.Tags.Builder, com.amit.webster.api.WebPageUserStat.WebPageUserStats.TagsOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.amit.webster.api.WebPageUserStats)
    }

    static {
      defaultInstance = new WebPageUserStats(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.amit.webster.api.WebPageUserStats)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amit_webster_api_WebPageUserStats_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amit_webster_api_WebPageUserStats_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amit_webster_api_WebPageUserStats_Tags_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025WebPageUserStat.proto\022\024com.amit.webste" +
      "r.api\"\303\001\n\020WebPageUserStats\022\016\n\006userId\030\007 \002" +
      "(\t\022\023\n\013completeUrl\030\001 \002(\t\022\017\n\007baseUrl\030\002 \002(\t" +
      "\022\016\n\006header\030\003 \002(\t\022\014\n\004like\030\004 \002(\010\022\014\n\004note\030\005" +
      " \001(\t\0228\n\003tag\030\006 \003(\0132+.com.amit.webster.api" +
      ".WebPageUserStats.Tags\032\023\n\004Tags\022\013\n\003tag\030\001 " +
      "\001(\tB\'\n\024com.amit.webster.apiB\017WebPageUser" +
      "Stat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_amit_webster_api_WebPageUserStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amit_webster_api_WebPageUserStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amit_webster_api_WebPageUserStats_descriptor,
        new java.lang.String[] { "UserId", "CompleteUrl", "BaseUrl", "Header", "Like", "Note", "Tag", });
    internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor =
      internal_static_com_amit_webster_api_WebPageUserStats_descriptor.getNestedTypes().get(0);
    internal_static_com_amit_webster_api_WebPageUserStats_Tags_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amit_webster_api_WebPageUserStats_Tags_descriptor,
        new java.lang.String[] { "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
